@host = http://localhost:5212

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "pdu@gmail.com",
    "password" : "pdu123"
}

